"""add authors

Revision ID: e3778aac7c80
Revises: ff3998a99799
Create Date: 2024-11-14 16:30:34.437777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3778aac7c80'
down_revision = 'ff3998a99799'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',                    
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_table('authors')
